### PR TITLE
som docs update

### PR DESCRIPTION
**Pull request by Luxonis-David**
Updated SOM datasheets:
- added 2085 variants 
- updated naming SOM naming convention

### CODE REVIEW

**Comment by Luxonis-David** [comment]
@cafemoloko / @Erol444  we should add OAK-SOM-IoT to the page and correct broken, links on SOM pages 
image

**Comment by Luxonis-Brandon** [comment]
Thank you.  Looks like a great update to me!

**Review by cafemoloko — APPROVED** [review]
LGTM, thanks!

**Comment by Luxonis-David** [comment]
@Erol444 can we merge this?

**Comment by Erol444** [comment]
> @Erol444 can we merge this?

@Luxonis-David  sure, could you just add an issue to add OAK-SOM-IOT to the docs so we won't forget? I can add some info, but it would be great if you would add more HW specific info as well (how it boots, from where, storage available, and other stuff you find relevant)

**Review by Erol444 — APPROVED** [review]

**Pull request merged**
