### PR TITLE
documentation revamp - product names

### PR DESCRIPTION
**Pull request by cafemoloko**
[DRAFT] 

- new categories
- new product names

### CODE REVIEW

**Comment by Erol444** [comment]
Thanks for your efforts! Just wanted to put it forward: we also need to update Discord channels to match these names.
And one thing I noticed, isn't this OAK-1 on the picture:
image
Then on the page, we have images of OAK-1-Modular and OAK-1-PCBA (so OAK-1 without the enclosure). Am I missing something?
Also a bit of a nitpick: if we name it `POE`, we should name the esp32 versions as `IOT`, not `IoT`. Consistency:)

**Comment by cafemoloko** [comment]
@Luxonis-Brandon, what do you think about @Erol444 comment regarding `IoT` names?
@Erol444 - thanks for the feedback - I'm working on changing images.

**Comment by Luxonis-Brandon** [comment]
Thanks @Erol444 on all this.  

Yes, we should probably go with @Erol444 suggestion on POE and IOT for consistency.  Let's do it.

Now on this:
image

The title should be "OAK-1" and the picture should be of "OAK-1".  An example photo of OAK-1 is below:

image


So the point of Hardware documentation now is to share specs about our products, information on them like size, dimensions, camera specs (such as FOV, etc.). 

So on OAK-D and OAK-1 we should have information like below (and probably these figures):

image


So let's remove any and all mention of BK1096 and OAK-1-Modular etc. from the docs completely and in every way.  I think it's confusing the subject on OAK-1.  So to make it clearer - any/all BK1096, OAK-1-Modular, etc. should be completely removed form the docs.

I think this will make it clearer to us all that we're just wanting to cover OAK-1 when we cover OAK-1, and nothing else.  And then later, once we get OAK-1 doc in a good place, we can re-evaluate how to cover the modular-board version, BK1096.  But for now we should remove all mention of it from our docs pages.

**Comment by Luxonis-Brandon** [comment]
Oh and @cafemoloko - could you update the OAK-D-POE photo to the production model that has the fully blacked out front?

image

And do this for any photos of it?  (I.e. the kind shown below, but doesn't have to be this exact photo)

**Comment by Luxonis-Brandon** [comment]
I'm realizing we should probably merge this, so the names are a better match.  And then continue to do iterative improvements from there.  So I'm going to do that in a second here.  And we can improve from there.

**Review by Luxonis-Brandon — APPROVED** [review]
Looks good for initial renaming.  And then we can improve off of this.  Just approving now (and then merging) to get the names to match shop.luxonis.com

**Pull request merged**
