### PR TITLE
OAK-1-PCBA added

### PR DESCRIPTION
**Pull request by cafemoloko**
Added to the main page and removed unrelated photos of the board.
image

### CODE REVIEW

**Review by Erol444 — CHANGES_REQUESTED** [review]
The BK1096 is not OAK-1-PCBA - it's the OAK-1-modular. So Like OAK-1-PCBA but it has SOM on the back instead of the VPU directly on the pcb.
I'm really not sure if there is any value to adding OAK-1-PCBA docs, I would rather document OAK-1-modular (not high priority), as that design is opensource.
Also would move the oak-1-modular to the Misc (at the bottom, where oak-d-pcba is) in the index.rst

**Comment by Luxonis-David** [comment]
Yes as you are saying @Erol444, we should separate those clearly, @cafemoloko I believe we synced on this already?
We were talking about adding BK1096 ask OAK-1-OSD (open source design) but if we already have a name OAK-D-Modular we should maybe keep that one (wasn't aware of that). 
Thoughts @Erol444?
So please make sure that the info on OAK-1-PCBA (BW1093) are only regarding the OAK-1-PCBA and the same for OAK-1-Modular when we get a chance to add it to the docs a well.

**Comment by cafemoloko** [comment]
Thanks, @Erol444 and @Luxonis-David I will swap the docs (OAK-1-PCBA and OAK-1-OSD). We should have OAK-1-PCBA in the docs because we sell that device.

**Comment by Erol444** [comment]
Well it's exactly the same as the OAK-1, just with the enclosure instead of the heatsink. So the only added value would be if we had dimensions in those docs.

**Comment by cafemoloko** [comment]
We know that, but new users/clients might not be aware of that, @Erol444 . Agreed on adding dimensions and weight.

**Comment by Erol444** [comment]
We have recently removed OAK-D-PCBA from docs page, so I am closing this PR as well.

**Pull request closed without merging**
