### PR TITLE
Add y-adapter enclosure stp files.

### PR DESCRIPTION
**Pull request by sungtzuwen**

### CODE REVIEW

**Comment by Erol444** [comment]
Should we have enclosure .step files in `/Mechanical` folder? Since we have some in a folder of the corresponding product (eg. OAK-D) and some in `/Mechanical`.

**Comment by Luxonis-David** [comment]
Just adding enclosures for now, we should move those to pertinent folders later. 
CC: @sungtzuwen

**Review by Erol444 — CHANGES_REQUESTED** [review]
As David mentioned, enc step files should be in their own folders. I will fix this in the following days and we can close this PR then.

**Comment by Erol444** [comment]
Lets close this PR and delete the brach

**Pull request closed without merging**
