### PR TITLE
BW1099 & BW2099 added

### PR DESCRIPTION
**Pull request by cafemoloko**
Descriptions based on datasheets.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
How do I see the page preview again for these?

**Comment by cafemoloko** [comment]
> How do I see the page preview again for these?

@Luxonis-Brandon I'll make a preview, give me a sec

**Comment by Luxonis-Brandon** [comment]
Thanks.  Oh and so any documentation PR that is up for review I think should have a preview.  (Unless there is some other WYSIWYG way to check it that I'm missing - and if so, please let me know.)

**Comment by cafemoloko** [comment]
> Thanks. Oh and so any documentation PR that is up for review I think should have a preview. (Unless there is some other WYSIWYG way to check it that I'm missing - and if so, please let me know.)

You're right and I should've built the preview earlier. The other way to see the changes would be fetching the branch and build locally. Preview [here](https://docs.luxonis.com/projects/hardware/en/latest/).

**Review by Luxonis-Brandon — APPROVED** [review]
LGTM

**Pull request merged**
